name: Build EAs

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Wine + MetaTrader compiler
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y wine64 wine32 unzip wget
          mkdir -p ~/mt4 ~/mt5

          # MT4 compiler
          wget -q https://download.mql5.com/cdn/web/metaquotes.software.corp/mt4/mt4.zip -O mt4.zip
          unzip -q mt4.zip -d ~/mt4 || true

          # MT5 compiler
          wget -q https://download.mql5.com/cdn/web/metaquotes.software.corp/mt5/mt5.zip -O mt5.zip
          unzip -q mt5.zip -d ~/mt5 || true

      - name: Compile MQL4 (if any)
        run: |
          mkdir -p build/mt4
          for f in $(find . -name "*.mq4"); do
            echo "Compiling $f ..."
            wine ~/mt4/metaeditor.exe /compile:"$f" /log
            cp "\${f%.mq4}.ex4" build/mt4/ || true
          done

      - name: Compile MQL5 (if any)
        run: |
          mkdir -p build/mt5
          for f in $(find . -name "*.mq5"); do
            echo "Compiling $f ..."
            wine ~/mt5/metaeditor64.exe /compile:"$f" /log
            cp "\${f%.mq5}.ex5" build/mt5/ || true
          done

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: compiled-eas
          path: build/**
